# Generated by Django 4.2.29 on 2026-03-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0005_auto_20190907_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="o365_event_id",
            field=models.CharField(blank=False, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="room",
            name="o365_calendar_email",
            field=models.EmailField(blank=False, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="artifax_id",
            field=models.IntegerField(blank=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="artifax_id",
            field=models.IntegerField(blank=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="artifax_id",
            field=models.IntegerField(blank=False, null=True, unique=True),
        ),
    ]
