# Generated by Django 4.2.29 on 2026-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0006_o365_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="allow_tablet_booking",
            field=models.BooleanField(
                default=False,
                help_text="Allow adhoc bookings to be made from the tablet display screen.",
            ),
        ),
    ]
