# Generated by Django 4.2.29 on 2026-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0010_remove_artifax"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, unique=True, verbose_name="IP address"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, unique=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="allow_booking",
            field=models.BooleanField(
                default=False,
                help_text="Allow adhoc bookings to be made from the display screen.",
            ),
        ),
    ]
