# Generated by Django 4.2.29 on 2026-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0011_building_ip_address_room_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="default_display",
            field=models.CharField(
                choices=[("grid", "Grid"), ("foyer", "Foyer")],
                default="grid",
                max_length=10,
            ),
        ),
    ]
