# Generated by Django 4.2.29 on 2026-04-15 15:40

from django.db import migrations, models
import django.db.models.deletion


def migrate_ip_addresses_forward(apps, schema_editor):
    """Copy existing ip_address fields from Room and Building into the new IpAddress model."""
    Building = apps.get_model("room_schedules", "Building")
    Room = apps.get_model("room_schedules", "Room")
    IpAddress = apps.get_model("room_schedules", "IpAddress")

    for building in Building.objects.exclude(ip_address__isnull=True).exclude(ip_address=""):
        IpAddress.objects.create(ip_address=building.ip_address, building=building)

    for room in Room.objects.exclude(ip_address__isnull=True).exclude(ip_address=""):
        IpAddress.objects.create(ip_address=room.ip_address, room=room)


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0012_building_default_display"),
    ]

    operations = [
        # 1. Create the new IpAddress model
        migrations.CreateModel(
            name="IpAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="IP address"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_addresses",
                        to="room_schedules.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_addresses",
                        to="room_schedules.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP address",
                "verbose_name_plural": "IP addresses",
            },
        ),
        migrations.AddConstraint(
            model_name="ipaddress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("building__isnull", True), ("room__isnull", False)),
                    models.Q(("building__isnull", False), ("room__isnull", True)),
                    _connector="OR",
                ),
                name="ip_address_room_xor_building",
            ),
        ),
        # 2. Migrate existing data
        migrations.RunPython(migrate_ip_addresses_forward, migrations.RunPython.noop),
        # 3. Remove old fields
        migrations.RemoveField(
            model_name="building",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="room",
            name="ip_address",
        ),
    ]
