# Generated by Django 4.2.29 on 2026-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0013_ip_address_model_multiple_ips"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "default_display",
                    models.CharField(
                        choices=[("grid", "Grid"), ("foyer", "Foyer")],
                        default="grid",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["building", "name"],
            },
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_groups",
                to="room_schedules.building",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="room_schedules.room"
            ),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="room_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ip_addresses",
                to="room_schedules.roomgroup",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="ipaddress",
            name="ip_address_room_xor_building",
        ),
        migrations.AddConstraint(
            model_name="ipaddress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("building__isnull", True),
                        ("room__isnull", False),
                        ("room_group__isnull", True),
                    ),
                    models.Q(
                        ("building__isnull", False),
                        ("room__isnull", True),
                        ("room_group__isnull", True),
                    ),
                    models.Q(
                        ("building__isnull", True),
                        ("room__isnull", True),
                        ("room_group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ip_address_exactly_one_target",
            ),
        ),
    ]
