# Generated by Django 4.2.29 on 2026-04-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0014_roomgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="missing_from_tenant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="o365_building_hint",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="room_schedules.building",
            ),
        ),
    ]
