# Generated by Django 4.2.29 on 2026-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0015_o365_room_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="no_calendar_access",
            field=models.BooleanField(default=False),
        ),
    ]
