# Generated by Django 4.2.29 on 2026-04-19 12:50

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def split_tenant_inventory_off_room(apps, schema_editor):
    """Forward: copy tenant-side Room fields into new O365Room rows and
    delete unassigned Room rows (they live only in O365Room from now on).
    """
    Room = apps.get_model("room_schedules", "Room")
    O365Room = apps.get_model("room_schedules", "O365Room")

    for room in Room.objects.exclude(o365_calendar_email__isnull=True).exclude(o365_calendar_email=""):
        O365Room.objects.update_or_create(
            email=room.o365_calendar_email,
            defaults={
                "name": room.name[:200],
                "building_hint": room.o365_building_hint or "",
                "no_calendar_access": room.no_calendar_access,
                "missing_from_tenant": room.missing_from_tenant,
            },
        )

    orphans = Room.objects.filter(building__isnull=True, o365_calendar_email__isnull=True)
    orphan_count = orphans.count()
    if orphan_count:
        logger.warning(
            "0017_o365_room_and_split_data: deleting %d Room row(s) with no building "
            "and no O365 email — these rows are unreachable and unexpected.",
            orphan_count,
        )
        orphans.delete()

    Room.objects.filter(building__isnull=True).delete()


def recombine_tenant_inventory_into_room(apps, schema_editor):
    """Reverse: for each O365Room without a matching Room, recreate an
    unassigned Room carrying the tenant fields; then drop all O365Room rows.
    """
    Room = apps.get_model("room_schedules", "Room")
    O365Room = apps.get_model("room_schedules", "O365Room")

    assigned_emails = set(
        Room.objects.exclude(o365_calendar_email__isnull=True)
                    .exclude(o365_calendar_email="")
                    .values_list("o365_calendar_email", flat=True)
    )

    for o365 in O365Room.objects.all():
        if o365.email in assigned_emails:
            Room.objects.filter(o365_calendar_email=o365.email).update(
                o365_building_hint=o365.building_hint,
                no_calendar_access=o365.no_calendar_access,
                missing_from_tenant=o365.missing_from_tenant,
            )
            continue
        Room.objects.create(
            name=o365.name[:100],
            building=None,
            o365_calendar_email=o365.email,
            o365_building_hint=o365.building_hint,
            no_calendar_access=o365.no_calendar_access,
            missing_from_tenant=o365.missing_from_tenant,
        )

    O365Room.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0016_room_no_calendar_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="O365Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "building_hint",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("no_calendar_access", models.BooleanField(default=False)),
                ("missing_from_tenant", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["building_hint", "name"],
            },
        ),
        migrations.RunPython(
            split_tenant_inventory_off_room,
            recombine_tenant_inventory_into_room,
        ),
    ]
