# Generated by Django 4.2.29 on 2026-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0018_room_drop_o365_fields_and_require_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Operator-facing label. Leave blank to follow the O365 name.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                help_text="Canonical O365 displayName. Auto-refreshed by the daily sync for O365-backed rooms.",
                max_length=200,
            ),
        ),
    ]
