# Generated by Django 4.2.29 on 2026-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0019_room_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="How long content is shown between screensaver appearances. Only applies when the screensaver is enabled.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=15,
                help_text="How long each page of long content is held before scrolling to the next. Applies regardless of whether the screensaver is enabled.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="screensaver_duration_seconds",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How long the screensaver image is shown before returning to content. Only applies when the screensaver is enabled.",
                verbose_name="Screensaver duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="screensaver_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the screensaver image periodically when this screen is displayed.",
                verbose_name="Enable screensaver",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="How long content is shown between screensaver appearances. Only applies when the screensaver is enabled.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=15,
                help_text="How long each page of long content is held before scrolling to the next. Applies regardless of whether the screensaver is enabled.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="screensaver_duration_seconds",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How long the screensaver image is shown before returning to content. Only applies when the screensaver is enabled.",
                verbose_name="Screensaver duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="screensaver_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the screensaver image periodically when this screen is displayed.",
                verbose_name="Enable screensaver",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="How long content is shown between screensaver appearances. Only applies when the screensaver is enabled.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=15,
                help_text="How long each page of long content is held before scrolling to the next. Applies regardless of whether the screensaver is enabled.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="screensaver_duration_seconds",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How long the screensaver image is shown before returning to content. Only applies when the screensaver is enabled.",
                verbose_name="Screensaver duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="screensaver_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the screensaver image periodically when this screen is displayed.",
                verbose_name="Enable screensaver",
            ),
        ),
    ]
