# Generated by Django 4.2.29 on 2026-05-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0020_building_content_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="Deprecated: no longer used. The HTML re-fetch interval is hardcoded to 300s, and booking changes are picked up within ~10s via state-hash polling.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=20,
                help_text="How long each page is held before scrolling to the next. On single-page screens (and any building view whose bookings fit on one page), this also controls how often the screensaver appears: content shows for this duration, screensaver shows for the screensaver duration, then the cycle repeats.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="Deprecated: no longer used. The HTML re-fetch interval is hardcoded to 300s, and booking changes are picked up within ~10s via state-hash polling.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How long each page is held before scrolling to the next. Room screens are almost always single-page, so in practice this also controls how often the screensaver appears: content shows for this duration, screensaver shows for the screensaver duration, then the cycle repeats.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="roomgroup",
            name="content_duration_seconds",
            field=models.PositiveIntegerField(
                default=600,
                help_text="Deprecated: no longer used. The HTML re-fetch interval is hardcoded to 300s, and booking changes are picked up within ~10s via state-hash polling.",
                verbose_name="Content duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="roomgroup",
            name="pagination_duration_seconds",
            field=models.PositiveIntegerField(
                default=20,
                help_text="How long each page is held before scrolling to the next. On single-page screens (and any group view whose bookings fit on one page), this also controls how often the screensaver appears: content shows for this duration, screensaver shows for the screensaver duration, then the cycle repeats.",
                verbose_name="Pagination duration (seconds)",
            ),
        ),
    ]
