# Generated by Django 4.2.29 on 2026-05-11 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_schedules", "0021_alter_building_content_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="grid_end_hour",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Last hour shown on the grid's time bar (1–24). Must be greater than the start hour.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Grid end hour",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="grid_start_hour",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="First hour shown on the grid's time bar (0–23, 24-hour clock). Narrower ranges give each event more horizontal space; EdGEL's reference uses 8–18 (a 10-hour day). Events outside this window are clipped.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name="Grid start hour",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="grid_end_hour",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Last hour shown on the grid's time bar (1–24). Must be greater than the start hour.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Grid end hour",
            ),
        ),
        migrations.AddField(
            model_name="roomgroup",
            name="grid_start_hour",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="First hour shown on the grid's time bar (0–23, 24-hour clock). Narrower ranges give each event more horizontal space; EdGEL's reference uses 8–18 (a 10-hour day). Events outside this window are clipped.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name="Grid start hour",
            ),
        ),
    ]
