# Generated by Django 4.2.29 on 2026-06-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "room_schedules",
            "0022_building_grid_end_hour_building_grid_start_hour_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="default_display",
            field=models.CharField(
                choices=[("grid", "Grid"), ("foyer", "Foyer")],
                default="grid",
                help_text="Default view for screens showing this building: Grid (hour-by-hour timetable) or Foyer (summary list).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the booking is cancelled. Maintained automatically by the O365 sync.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="o365_event_id",
            field=models.CharField(
                help_text="Internal O365 sync key — do not edit.",
                max_length=500,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="building",
            field=models.ForeignKey(
                blank=True,
                help_text="Set exactly one of room, building, or room group — this IP drives that one target's display.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ip_addresses",
                to="room_schedules.building",
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Set exactly one of room, building, or room group — this IP drives that one target's display.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ip_addresses",
                to="room_schedules.room",
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="room_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Set exactly one of room, building, or room group — this IP drives that one target's display.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ip_addresses",
                to="room_schedules.roomgroup",
            ),
        ),
        migrations.AlterField(
            model_name="o365room",
            name="building_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Building name suggested by O365, used to help assign this mailbox to a building. Informational.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="o365room",
            name="missing_from_tenant",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically when this mailbox is no longer found in O365 (e.g. deleted).",
            ),
        ),
        migrations.AlterField(
            model_name="o365room",
            name="no_calendar_access",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically when the daily sync cannot read this mailbox's calendar.",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="o365_calendar_email",
            field=models.EmailField(
                blank=True,
                help_text="The room's O365 mailbox address. Set this to pull bookings from Outlook/O365; leave blank for a manually-managed room.",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="roomgroup",
            name="default_display",
            field=models.CharField(
                choices=[("grid", "Grid"), ("foyer", "Foyer")],
                default="grid",
                help_text="Default view for screens showing this group: Grid (hour-by-hour timetable) or Foyer (summary list).",
                max_length=10,
            ),
        ),
    ]
