# Generated by Django 4.2.29 on 2026-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "room_schedules",
            "0023_alter_building_default_display_alter_event_cancelled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sensitivity",
            field=models.CharField(
                default="normal",
                help_text="O365 sensitivity (normal/personal/private/confidential). Maintained automatically by the O365 sync.",
                max_length=20,
            ),
        ),
    ]
